# Generated by Django 6.0.2 on 2026-02-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='website',
        ),
    ]
