# Generated by Django 6.0.2 on 2026-02-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_organizer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('physical', 'Physical Event'), ('online', 'Online Event'), ('hybrid', 'Hybrid Event')], default='physical', max_length=10),
        ),
    ]
