# Generated by Django 6.0.2 on 2026-02-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='lga',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='lagos', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('lagos', 'Lagos'), ('abuja', 'Abuja (FCT)')], default='lagos', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LGA',
        ),
    ]
