# Generated by Django 6.0.2 on 2026-02-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_newsletteremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
