# Generated by Django 6.0.2 on 2026-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('', 'Select an option'), ('ticket', 'Ticket Inquiry'), ('organizer', 'Organizer Partnership'), ('support', 'General Support')], max_length=20),
        ),
    ]
