from django.urls import path
from . import views 

urlpatterns = [
    path('', views.home, name='home'),
    path('user/signup/', views.user_signup, name='signup'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.user_logout, name='logout'),
    path("user/login/", views.user_login, name="user_login"),
    path("organizer/signup/", views.organizer_signup, name="organizer_signup"),
    path('organizer/login/', views.organizer_login, name='organizer_login'),
    path('organizer/dashboard/', views.org_dashboard, name='org_dashboard'),
    path("organizer/logout/", views.organizer_logout, name="organizer_logout"),
    path('create/event/', views.create_event, name="create_event"),
    path('event/<int:event_id>/', views.event_detail, name="event_detail"),
    path('event/list/', views.events_list, name='events_list'),
    path('event/<int:event_id>/confirm/', views.booking_confirm, name='booking_confirm'),
    path("pay/<int:order_id>/", views.initialize_payment, name="initialize_payment"),
    path("verify-payment/", views.verify_payment, name="verify_payment"),
    path("payment-success/", views.payment_success, name="payment_success"),
    path("payment-failed/", views.payment_failed, name="payment_failed"),
    path('org/my_events/', views.my_events, name='my_events'),
    path('edit/<int:pk>/', views.edit_event, name='edit_event'),
    path('delete/<int:pk>/',views.delete_event,name='delete_event'),
    path("org/profile/",views.organizer_profile,name="organizer_profile"),
    path('organizer/tickets/', views.organizer_tickets, name='organizer_tickets'),
    path('org/payouts/', views.payout, name='payout'),
    path('upcoming-events/', views.upcoming_events, name='upcoming_events'),
    path('my_tickets/', views.my_tickets, name='my_tickets'),
    path('past_events/', views.past_events, name='past_events'),
    path('saved_events/', views.saved_events, name='saved_events'),
    path('profile-settings/', views.edit_profile, name='edit_profile'),
    path('event/<int:event_id>/toggle-save/', views.toggle_save_event, name='toggle_save_event'),
    path('newsletter/subscribe/', views.newsletter_subscribe, name='newsletter_subscribe'),
    path('about/', views.about, name='about'),
]